name: Version Check

on:
  push:

jobs:
  version_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.1

      - name: Version Check
        run: python --version
